name: quotesapi deployment on aws

on:
  push:
    branches:
      - main
  
jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
  - name: checkout
  - uses: actions/checkout@v1
  
  - name: Install dependencies
  - run: npm ci
  
  - name: Build application
  - run: npm run build
  
  - name: Run test
  - run: npm test
  
  - name: Configure-aws-credentials
  - uses: aws-actions/configure-aws-credential@v1
    with: 
     aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
     aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
     aws-origin: us-east-1
     
  - name: deploy static site to s3 bucket
    run: aws s3 sync . s3://quotes-api --delete
